name: newapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^4.0.0
  meta: ^1.15.0
  material_color_utilities: ^0.8.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  
  

dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true
  assets:
    - android/assets/a.avif
    - android/assets/b.avif
    - android/assets/c.avif
    - android/assets/d.avif
    - android/assets/e.avif
    - android/assets/f.avif
    - android/assets/g.avif
    - android/assets/h.avif
    - android/assets/i.avif
    - android/assets/j.avif
    - android/assets/k.avif
    - android/assets/l.avif
    - android/assets/m.avif
    - android/assets/n.avif
    - android/assets/o.avif
    - android/assets/p.avif
    - android/assets/q.avif
    - android/assets/r.avif
    - android/assets/s.avif
    - android/assets/t.avif
    - android/assets/u.avif
    - android/assets/v.avif
    - android/assets/w.avif
