name: newapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_lints: ^4.0.0
  meta: ^1.15.0
  material_color_utilities: ^0.8.0
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any
  
  

dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/a.jpg
    - assets/c.jpg
    - assets/d.jpg
    - assets/e.jpg
    - assets/b.jpg
    - assets/f.jpg
    - assets/g.jpg
    - assets/h.jpg
    - assets/i.jpg
    - assets/j.jpg
    - assets/k.jpg
    - assets/l.jpg
    - assets/m.jpg
    - assets/n.jpg
    - assets/o.jpg
    - assets/p.jpg
    - assets/q.jpg
    - assets/r.jpg
    - assets/s.jpg
    - assets/t.jpg
    - assets/u.jpg
    - assets/v.jpg
    - assets/w.jpg